apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  labels:
    app: cloud-native-project
  name: cloud-native-project
  namespace: nju04
spec:
  replicas: 1  #运行容器的副本数
  selector:
    matchLabels:
      app: cloud-native-project
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: cloud-native-project
    spec:
      containers: #docker容器的配置
      - image: harbor.edu.cn/nju04/cloud-native-project:{VERSION} #pull镜像的地址
        name: cloud-native-project
      imagePullSecrets:
        - name: nju04
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-native-project
  namespace: nju04
  labels:
    app: cloud-native-project
spec:
  type: NodePort
  selector:
    app: cloud-native-project
  ports:
  - name: tcp
    nodePort: 31005  #host's port
    protocol: TCP
    port: 8080  #service's port
    targetPort: 8080  #target pod's port
